apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score-backend-deployment
  labels:
    app: credit-score-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-score-backend-deployment
  template:
    metadata:
      labels:
        app: credit-score-backend-deployment
    spec:
      containers:
        - name: credit-score-backend
          image: hub.umceko.com/credit/backend:0.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score-frontend-deployment
  labels:
    app: credit-score-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-score-frontend-deployment
  template:
    metadata:
      labels:
        app: credit-score-frontend-deployment
    spec:
      containers:
        - name: credit-score-frontend
          image: hub.umceko.com/credit/frontend:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: credit-score-backend-service
spec:
  selector:
    app: credit-score-backend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: credit-score-frontend-service
spec:
  selector:
    app: credit-score-frontend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-score-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: credit.umceko.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: credit-score-backend-service
                port:
                  number: 80
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: credit-score-frontend-service
                port:
                  number: 80


